
USE stackexchange;

DROP TABLE IF EXISTS Badges;
DROP TABLE IF EXISTS Comments;
DROP TABLE IF EXISTS Posts;
DROP TABLE IF EXISTS PostHistory;
DROP TABLE IF EXISTS PostLinks;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Votes;
DROP TABLE IF EXISTS Tags;
